import nodemailer from 'nodemailer'
import { getDatabase } from '@storage/Database'
import { getAllSettings } from '../main/store'
import { buildMeetingMarkdown } from './markdown'
import { escapeHtml } from './pdfTemplate'

// =============================================================================
// EmailSender — sends a meeting brief via SMTP (nodemailer). SMTP config comes
// from settings. Sends both a plain-text (markdown) and a light HTML body.
// =============================================================================

function htmlBody(meeting: Record<string, any>): string {
  const s = (meeting.summary ?? {}) as Record<string, any>
  const list = (items: string[] = []) =>
    items.length ? `<ul>${items.map((i) => `<li>${escapeHtml(i)}</li>`).join('')}</ul>` : '<p>—</p>'
  return `
    <div style="font-family:Arial,sans-serif;color:#0A2540;max-width:640px">
      <h1 style="color:#0A2540">${escapeHtml(meeting.title || 'Meeting')}</h1>
      <p style="color:#3D5A80">${escapeHtml(s.tldr || '')}</p>
      <h3>Decisions</h3>${list(s.decisions)}
      <h3>Open Questions</h3>${list(s.openQuestions)}
      <hr/><p style="color:#7A95B8;font-size:12px">Generated by BriefOS</p>
    </div>`
}

export async function exportByEmail(meetingId: string, recipients: string[]): Promise<void> {
  console.log('[email] exporting meeting', meetingId, '→', recipients)
  if (!recipients || recipients.length === 0) throw new Error('No recipients provided')

  const settings = getAllSettings()
  if (!settings.smtpHost) throw new Error('SMTP host not set (Settings → Integrations)')

  const meeting = getDatabase().getMeeting(meetingId)
  if (!meeting) throw new Error(`Meeting ${meetingId} not found`)

  const transport = nodemailer.createTransport({
    host: settings.smtpHost,
    port: settings.smtpPort || 587,
    secure: (settings.smtpPort || 587) === 465,
    auth: settings.smtpUser ? { user: settings.smtpUser, pass: settings.smtpPass } : undefined
  })

  try {
    await transport.sendMail({
      from: settings.emailFrom || settings.smtpUser,
      to: recipients.join(', '),
      subject: `Meeting Brief — ${meeting.title || 'Untitled'}`,
      text: buildMeetingMarkdown(meeting),
      html: htmlBody(meeting)
    })
    console.log('[email] sent')
  } catch (err) {
    console.error('[email] send failed', err)
    throw new Error(`Email export failed: ${(err as Error).message}`)
  }
}
