import type { ActionItem } from '@ai/SummaryEngine'

// =============================================================================
// Shared markdown builder for a meeting brief. Used by clipboard, Slack, and
// email exporters so the text format stays consistent.
// =============================================================================

function fmtDuration(seconds: number): string {
  const h = Math.floor(seconds / 3600)
  const m = Math.floor((seconds % 3600) / 60)
  return h > 0 ? `${h}h ${m}m` : `${m}m`
}

export function buildMeetingMarkdown(meeting: Record<string, any>): string {
  const s = (meeting.summary ?? {}) as Record<string, any>
  const lines: string[] = []

  lines.push(`# ${meeting.title || 'Untitled Meeting'}`)
  lines.push('')
  lines.push(
    `*${new Date(meeting.started_at).toLocaleString()} · ${fmtDuration(meeting.duration_s ?? 0)} · ${
      meeting.type || 'other'
    }*`
  )
  lines.push('')

  if (s.tldr) {
    lines.push('## TL;DR')
    lines.push(s.tldr)
    lines.push('')
  }
  if (s.context) {
    lines.push('## Context')
    lines.push(s.context)
    lines.push('')
  }

  const decisions: string[] = s.decisions ?? []
  if (decisions.length) {
    lines.push('## Decisions')
    decisions.forEach((d) => lines.push(`- ${d}`))
    lines.push('')
  }

  const actions: ActionItem[] = s.actionItems ?? []
  if (actions.length) {
    lines.push('## Action Items')
    actions.forEach((a) => {
      const due = a.deadline ? ` _(due ${a.deadline})_` : ''
      lines.push(`- **${a.person}** [${a.priority}] — ${a.task}${due}`)
    })
    lines.push('')
  }

  const questions: string[] = s.openQuestions ?? []
  if (questions.length) {
    lines.push('## Open Questions')
    questions.forEach((q) => lines.push(`- ${q}`))
    lines.push('')
  }

  const keywords: string[] = s.keywords ?? []
  if (keywords.length) {
    lines.push('## Keywords')
    lines.push(keywords.join(', '))
    lines.push('')
  }

  lines.push('---')
  lines.push('_Generated by BriefOS_')
  return lines.join('\n')
}
