// =============================================================================
// Shared PDF template — common <head>, fonts, and BriefOS design-token CSS used
// by both PDFRenderer (meeting brief) and PeriodReportPDF. Keeps export styling
// consistent and in sync with the renderer design system. Never hardcode colors
// in the individual exporters; build markup with the classes defined here.
// =============================================================================

/** Escape user/content text for safe HTML interpolation. */
export function escapeHtml(value: unknown): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

// Design tokens mirrored from tailwind.config.ts / CLAUDE.md.
const BASE_CSS = `
  @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@500;700;800&family=DM+Sans:wght@400;500;600&family=DM+Mono:wght@400;500&display=swap');

  :root {
    --bg: #F7F9FC;
    --surface: #FFFFFF;
    --blue-tint: #EBF3FF;
    --accent: #1A56DB;
    --blue-deep: #0A2540;
    --border: #D8E5F5;
    --text: #0A2540;
    --text2: #3D5A80;
    --text3: #7A95B8;
    --green: #0EA874;
    --amber: #D97706;
    --red: #E53E3E;
  }

  * { box-sizing: border-box; margin: 0; padding: 0; }

  body {
    font-family: 'DM Sans', system-ui, sans-serif;
    color: var(--text);
    background: var(--surface);
    font-size: 13px;
    line-height: 1.55;
    -webkit-print-color-adjust: exact;
    print-color-adjust: exact;
  }

  h1, h2, h3 { font-family: 'Outfit', system-ui, sans-serif; color: var(--blue-deep); }
  h1 { font-size: 26px; font-weight: 800; letter-spacing: -0.02em; }
  h2 { font-size: 16px; font-weight: 700; margin-bottom: 10px; }
  h3 { font-size: 13px; font-weight: 700; }

  .mono { font-family: 'DM Mono', ui-monospace, monospace; }
  .muted { color: var(--text3); }
  .secondary { color: var(--text2); }

  .hero {
    background: var(--blue-deep);
    color: #fff;
    padding: 28px 32px;
    border-radius: 16px;
    margin-bottom: 20px;
  }
  .hero h1 { color: #fff; }
  .hero .meta { color: #B9CBE4; font-size: 12px; margin-top: 6px; }

  .stat-row { display: flex; gap: 28px; margin-top: 18px; }
  .stat .num { font-family: 'Outfit', sans-serif; font-size: 22px; font-weight: 800; }
  .stat .lbl { font-size: 11px; color: #B9CBE4; text-transform: uppercase; letter-spacing: 0.04em; }

  .card {
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 10px;
    padding: 18px 20px;
    margin-bottom: 14px;
    page-break-inside: avoid;
  }

  .grid2 { display: grid; grid-template-columns: 1fr 1fr; gap: 14px; }

  ul.clean { list-style: none; }
  ul.clean li {
    padding: 7px 0 7px 18px;
    position: relative;
    border-bottom: 1px solid var(--border);
  }
  ul.clean li:last-child { border-bottom: none; }
  ul.clean li::before {
    content: '';
    position: absolute; left: 2px; top: 14px;
    width: 6px; height: 6px; border-radius: 50%;
    background: var(--accent);
  }

  .pill {
    display: inline-block;
    font-size: 10px; font-weight: 600;
    padding: 2px 8px; border-radius: 999px;
    background: var(--blue-tint); color: var(--accent);
  }
  .pill.high { background: #FDECEC; color: var(--red); }
  .pill.medium { background: #FEF3E2; color: var(--amber); }
  .pill.low { background: #E6F7F0; color: var(--green); }

  .action { padding: 9px 0; border-bottom: 1px solid var(--border); }
  .action:last-child { border-bottom: none; }
  .action .who { font-weight: 600; }
  .action .when { font-size: 11px; color: var(--text3); }

  .keywords { display: flex; flex-wrap: wrap; gap: 6px; }
  .keywords .kw {
    font-size: 11px; padding: 3px 9px; border-radius: 999px;
    background: var(--blue-tint); color: var(--text2);
  }

  .section-title {
    font-family: 'Outfit', sans-serif; font-weight: 700;
    color: var(--blue-deep); font-size: 15px;
    margin: 18px 0 8px;
  }

  .footer {
    margin-top: 24px; padding-top: 12px;
    border-top: 1px solid var(--border);
    font-size: 10px; color: var(--text3);
    display: flex; justify-content: space-between;
  }
`

/** Wrap a body fragment into a full printable HTML document. */
export function renderDocument(title: string, bodyHtml: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${escapeHtml(title)}</title>
<style>${BASE_CSS}</style>
</head>
<body>
<div class="page">
${bodyHtml}
<div class="footer">
  <span>Generated by BriefOS</span>
  <span class="mono">${escapeHtml(new Date().toISOString().slice(0, 10))}</span>
</div>
</div>
</body>
</html>`
}

// --- Small markup helpers shared by the exporters ---------------------------

export function bulletList(items: unknown[], emptyText = 'None'): string {
  if (!items || items.length === 0) return `<p class="muted">${escapeHtml(emptyText)}</p>`
  return `<ul class="clean">${items.map((i) => `<li>${escapeHtml(i)}</li>`).join('')}</ul>`
}

export function priorityPill(priority: string): string {
  const p = ['high', 'medium', 'low'].includes(priority) ? priority : 'low'
  return `<span class="pill ${p}">${escapeHtml(p)}</span>`
}

export function keywordCloud(keywords: unknown[]): string {
  if (!keywords || keywords.length === 0) return '<p class="muted">None</p>'
  return `<div class="keywords">${keywords
    .map((k) => `<span class="kw">${escapeHtml(k)}</span>`)
    .join('')}</div>`
}
